title: GitFlags Docs
description: Official GitFlags documentation site
theme: just-the-docs

url: https://docs.gitflags.com

color_scheme: dark

aux_links:
  Check us out on GitHub!: https://github.com/gitflags/docs
